### ISSUE TITLE
Add a simple usage example

### ISSUE THREAD

**Issue by jmini** [britter/maven-plugin-development#40]
I would really appreciate to have an usage example somewhere.

The `GreetingMojo` from the maven documentation is sufficient:
https://maven.apache.org/guides/plugin/guide-java-plugin-development.html
And there is an usage example in a separated pom.

I have tried to start it [sample-maven-plugin](https://github.com/jmini/gradle-sandbox/tree/sample-maven-plugin/sample-maven-plugin). But it is not working.

At the end the relevant pieces could be included in the published documentation:
https://www.benediktritter.de/maven-plugin-development/#usage
Right now the explanations in the "usage" section are not enough for me (average gradle usage)

**Comment by jmini** [comment]
I got feedback from @britter on twitter:

>  All the plugin really does is create some files in the META-INF folder of the final jar which maven needs to detect the jar as a plugin.
> It would be great if you could explain a little bit more what does not work for you.
> Maybe you‘re struggling with using the build result in a Maven build? The simplest way to do that would be to use the `maven-publish` plugin and then use the `publishToMavenLocal` task to publish the Maven plugin to your local Maven repository.

Thank you a lot for the quick feedback. This is exactly what I assume the plugin would do.

I also tried to add the `maven-publish` but since I have the feeling my setup is already not correct for the `build` task I did not push that one yet. I am not a gradle power user (I continue to learn it) I thought I got something wrong.

This morning stuff is looking way better than yesterday ;-)
When I run `./gradlew build` in the `sample-maven-plugin` project linked above I get:

```
$ tree build
build
├── classes
│   └── java
│       └── main
│           ├── HelpMojo.class
│           └── sample
│               └── plugin
│                   └── GreetingMojo.class
├── generated
│   └── sources
│       ├── annotationProcessor
│       │   └── java
│       │       └── main
│       └── headers
│           └── java
│               └── main
├── libs
│   └── sample-maven-plugin-0.1.2.jar
├── mavenPlugin
│   ├── descriptor
│   │   └── META-INF
│   │       └── maven
│   │           ├── org.example
│   │           │   └── sample-maven-plugin
│   │           │       └── plugin-help.xml
│   │           └── plugin.xml
│   ├── helpMojo
│   │   └── HelpMojo.java
│   └── maven-plugin-help.properties
└── tmp
    ├── compileJava
    │   └── source-classes-mapping.txt
    └── jar
        └── MANIFEST.MF
```

Yesterday I had the feeling to have only a `tmp` and a `generated` folder inside the build folder. Seeing the `mavenPlugin` and the `libs` makes me confident that this will work…

---

Next steps for me add the `maven-publish` and the other steps requested (javadoc jar, source jar, pom customization and sign plugin) to get something that can be pushed on Maven Central.

---

Thank you a lot for your support. I will report here about my progress…

If the whole thing works for me I might be able to create a small PR with documentation improvements (you know for the beginner user that I am).

**Comment by britter** [comment]
Hi @jmini! 👋 Great to hear you're trying out this little plugin. I agree that the documentation is missing a getting started guide. I'm going to work on that.

Regarding your sample project: I think you're almost there. I assume you're coming from Maven and you're looking for the equivalent of `mvn install`. Gradle does not have a built in task to deploy to the local Maven repository. `./gradlew build` just assembles the build result in the `build` folder. So in order to use the Maven plugin that you're building you need to apply the `maven-publish` plugin and let it publish the plugin into your local Maven repository. Don't forget to set `group` in your `build.gradle[.kts]` file. After you applied the `maven-publish` plugin you can run `./gradlew publishToMavenLocal` to publish the maven plugin to the local Maven repository. From there it can be consumed by any Maven build on your machine.

The `maven-publish` plugin can also be used to publish to Maven central. There is an API for customizing the published POM. You can have a look at [this project of mine](https://github.com/britter/bean-validators/blob/master/buildSrc/src/main/kotlin/publishing-conventions.gradle.kts#L24-L54) where I did this.

If you need more help, don't hesitate to reach out. I'm also in the [Gradle community slack]( https://gradle.com/slack-invite) where we can have a direct conversation.

Cheers

**Comment by britter** [comment]
@jmini I've added a usage example. Let me know what you think.
